// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGAPrincipal.BDAdministrativa;

#nullable disable

namespace SIGAPrincipal.Migrations.DataAdministrativaMigrations
{
    [DbContext(typeof(DataAdministrativa))]
    [Migration("20260423033830_InitAdministrativa")]
    partial class InitAdministrativa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("administrativa")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGAPrincipal.BDAdministrativa.AsignacionUniversidadColaborador", b =>
                {
                    b.Property<int>("AsignacionUniversidadColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AsignacionUniversidadColaboradorId"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("integer");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("integer");

                    b.HasKey("AsignacionUniversidadColaboradorId");

                    b.ToTable("Asignaciones", "administrativa");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAdministrativa.Colaborador", b =>
                {
                    b.Property<int>("ColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ColaboradorId"));

                    b.Property<string>("Cargo")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ColaboradorId");

                    b.ToTable("Colaboradores", "administrativa");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAdministrativa.ConfiguracionUniversidad", b =>
                {
                    b.Property<int>("ConfiguracionUniversidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConfiguracionUniversidadId"));

                    b.Property<string>("ColoresTema")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("NombreInstitucional")
                        .HasColumnType("text");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("integer");

                    b.HasKey("ConfiguracionUniversidadId");

                    b.ToTable("ConfiguracionesUniversidad", "administrativa");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAdministrativa.HistorialSolicitud", b =>
                {
                    b.Property<int>("HistorialSolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialSolicitudId"));

                    b.Property<string>("Accion")
                        .HasColumnType("text");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("integer");

                    b.HasKey("HistorialSolicitudId");

                    b.ToTable("HistorialSolicitudes", "administrativa");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAdministrativa.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SolicitudId"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("EstadoSolicitud")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoSolicitud")
                        .HasColumnType("text");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("integer");

                    b.HasKey("SolicitudId");

                    b.ToTable("Solicitudes", "administrativa");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAdministrativa.Universidad", b =>
                {
                    b.Property<int>("UniversidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversidadId"));

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("UniversidadId");

                    b.ToTable("Universidades", "administrativa");
                });
#pragma warning restore 612, 618
        }
    }
}
