// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGAPrincipal.BDAcademico;

#nullable disable

namespace SIGAPrincipal.Migrations
{
    [DbContext(typeof(DataAcademico))]
    partial class DataAcademicoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("academico")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Asignatura", b =>
                {
                    b.Property<int>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AsignaturaId"));

                    b.Property<int>("CreditosAsignatura")
                        .HasColumnType("integer");

                    b.Property<int>("CuposAsignatura")
                        .HasColumnType("integer");

                    b.Property<string>("NombreAsignatura")
                        .HasColumnType("text");

                    b.HasKey("AsignaturaId");

                    b.ToTable("Asignaturas", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Calificacion", b =>
                {
                    b.Property<int>("CalificacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CalificacionId"));

                    b.Property<int>("InscripcionId")
                        .HasColumnType("integer");

                    b.Property<double>("Nota")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoNota")
                        .HasColumnType("text");

                    b.HasKey("CalificacionId");

                    b.ToTable("Calificaciones", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Docente", b =>
                {
                    b.Property<int>("DocenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocenteId"));

                    b.Property<string>("Especialidad")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("DocenteId");

                    b.ToTable("Docentes", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("CodigoEstudiante")
                        .HasColumnType("text");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Grupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GrupoId"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("DocenteId")
                        .HasColumnType("integer");

                    b.Property<int>("HorarioId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreGrupo")
                        .HasColumnType("text");

                    b.HasKey("GrupoId");

                    b.ToTable("Grupos", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.HistorialAcademico", b =>
                {
                    b.Property<int>("HistorialAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialAcademicoId"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("CreditosAsignatura")
                        .HasColumnType("integer");

                    b.Property<int>("Cupos")
                        .HasColumnType("integer");

                    b.Property<string>("NombreAsignatura")
                        .HasColumnType("text");

                    b.HasKey("HistorialAcademicoId");

                    b.ToTable("HistorialAcademicos", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HorarioId"));

                    b.Property<string>("Aula")
                        .HasColumnType("text");

                    b.Property<string>("Dia")
                        .HasColumnType("text");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.HasKey("HorarioId");

                    b.ToTable("Horarios", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Inscripcion", b =>
                {
                    b.Property<int>("InscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InscripcionId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfertaAcademicaId")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("InscripcionId");

                    b.ToTable("Inscripciones", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.OfertaAcademica", b =>
                {
                    b.Property<int>("OfertaAcademicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfertaAcademicaId"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("CuposDisponibles")
                        .HasColumnType("integer");

                    b.Property<int>("CuposMaximos")
                        .HasColumnType("integer");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("integer");

                    b.HasKey("OfertaAcademicaId");

                    b.ToTable("OfertasAcademicas", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Periodo", b =>
                {
                    b.Property<int>("PeriodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodoId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("NombrePeriodo")
                        .HasColumnType("text");

                    b.HasKey("PeriodoId");

                    b.ToTable("Periodos", "academico");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAcademico.Programa", b =>
                {
                    b.Property<int>("ProgramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProgramaId"));

                    b.Property<string>("NombrePrograma")
                        .HasColumnType("text");

                    b.HasKey("ProgramaId");

                    b.ToTable("Programas", "academico");
                });
#pragma warning restore 612, 618
        }
    }
}
