// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGAPrincipal.BDAutenticacion;

#nullable disable

namespace SIGAPrincipal.Migrations.DataAutenticacionMigrations
{
    [DbContext(typeof(DataAutenticacion))]
    [Migration("20260423034029_InitAutenticacion")]
    partial class InitAutenticacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("autenticacion")
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGAPrincipal.BDAutenticacion.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("PermisoId");

                    b.ToTable("Permisos", "autenticacion");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAutenticacion.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.HasKey("RolId");

                    b.ToTable("Roles", "autenticacion");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAutenticacion.RolPermiso", b =>
                {
                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<int>("PermisoId")
                        .HasColumnType("integer");

                    b.HasKey("RolId", "PermisoId");

                    b.ToTable("RolPermisos", "autenticacion");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAutenticacion.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContrasenaHash")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<int>("UniversidadId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios", "autenticacion");
                });

            modelBuilder.Entity("SIGAPrincipal.BDAutenticacion.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "RolId");

                    b.ToTable("UsuarioRoles", "autenticacion");
                });
#pragma warning restore 612, 618
        }
    }
}
